"""new column in M2M table

Revision ID: a62560470d34
Revises: acff771c69e6
Create Date: 2024-01-24 21:59:13.630897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62560470d34'
down_revision: Union[str, None] = 'acff771c69e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies_replies', sa.Column('cover_letter', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies_replies', 'cover_letter')
    # ### end Alembic commands ###
